# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 05:46
from __future__ import unicode_literals

import PatientScheduling.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NurseScheduleID', models.PositiveIntegerField(default=0)),
                ('ChairID', models.PositiveIntegerField(default=0)),
                ('StartTime', models.TimeField()),
                ('EndTime', models.TimeField()),
                ('SaveName', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ChemotherapyDrug',
            fields=[
                ('Name', models.CharField(max_length=60, primary_key=True, serialize=False, verbose_name=b'Name')),
                ('EarliestTime', models.TimeField(blank=True, null=True, verbose_name=b'Earliest Schedule Time')),
                ('LatestTime', models.TimeField(blank=True, null=True, verbose_name=b'Latest Schedule Time')),
                ('OtherRules', models.TextField(blank=True, null=True, verbose_name=b'Other Rules')),
            ],
            options={
                'verbose_name': 'Chemotherapy Drug',
                'verbose_name_plural': 'Chemotherapy Drugs',
            },
        ),
        migrations.CreateModel(
            name='NurseSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NurseID', models.PositiveIntegerField(null=True)),
                ('Team', models.CharField(default=b'A', max_length=1, validators=[PatientScheduling.models.model_one_letter])),
                ('StartTime', models.TimeField(default=b'08:00')),
                ('LunchTime', models.TimeField(default=b'12:00', null=True)),
                ('LunchDuration', models.PositiveIntegerField(default=60, null=True)),
                ('EndTime', models.TimeField(default=b'16:00')),
            ],
        ),
        migrations.CreateModel(
            name='NurseScheduleGroups',
            fields=[
                ('Name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Chairs', models.IntegerField()),
                ('UserCreated', models.BooleanField(default=True)),
                ('SavedDate', models.DateTimeField(auto_now=True, verbose_name=b'Created On')),
            ],
            options={
                'verbose_name': 'RN Schedule',
                'verbose_name_plural': 'RN Schedules',
            },
        ),
        migrations.CreateModel(
            name='SavedSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20, unique=True)),
                ('SavedDate', models.DateTimeField(auto_now=True)),
                ('NurseSchedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PatientScheduling.NurseScheduleGroups')),
            ],
        ),
        migrations.CreateModel(
            name='SavedTimeSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Duration', models.IntegerField(default=0)),
                ('Count', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='nurseschedule',
            name='ScheduleGroupName',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='PatientScheduling.NurseScheduleGroups'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='SavedSchedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PatientScheduling.SavedSchedule'),
        ),
    ]
