# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-16 17:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

from PatientScheduling.models import SavedTimeSlotGroup


class Migration(migrations.Migration):

    dependencies = [
        ('PatientScheduling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedTimeSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Duration', models.IntegerField(default=0)),
                ('Count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SavedTimeSlotGroup',
            fields=[
                ('Name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('SavedDate', models.DateTimeField(auto_now=True, verbose_name=b'Created On')),
            ],
            options={
                'verbose_name': 'Time Slots Input',
                'verbose_name_plural': 'Saved Time Slots Inputs',
            },
        ),
        migrations.AddField(
            model_name='SavedTimeSlot',
            name='Group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PatientScheduling.SavedTimeSlotGroup'),
        ),
        migrations.AddField(
            model_name='savedschedule',
            name='TimeSlots',
            field=models.ForeignKey(default=SavedTimeSlotGroup.objects.get(pk='dbChanges'), on_delete=django.db.models.deletion.CASCADE, to='PatientScheduling.SavedTimeSlotGroup'),
            preserve_default=False,
        ),
    ]
