# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-27 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PatientScheduling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemotherapydrug',
            name='EarliestTime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chemotherapydrug',
            name='LatestTime',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
