# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 05:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PatientScheduling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedTimeSlotGroup',
            fields=[
                ('Name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('SavedDate', models.DateTimeField(auto_now=True, verbose_name=b'Created On')),
            ],
            options={
                'verbose_name': 'Time Slots Input',
                'verbose_name_plural': 'Saved Time Slots Inputs',
            },
        ),
    ]
