# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 02:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PatientScheduling', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chemotherapydrug',
            name='id',
        ),
        migrations.AlterField(
            model_name='chemotherapydrug',
            name='Name',
            field=models.CharField(max_length=60, primary_key=True, serialize=False),
        ),
    ]
