# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PatientScheduling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompanyStartHours', models.TimeField()),
                ('CompanyEndHours', models.TimeField()),
                ('singleton_enforce', models.IntegerField(default=1, unique=True)),
            ],
        ),
    ]
