# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-20 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PatientScheduling', '0002_companyinformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChemotherapyDrug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=60, unique=True)),
                ('EarliestTime', models.TimeField()),
                ('LatestTime', models.TimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='CompanyInformation',
        ),
        migrations.AlterField(
            model_name='nurseschedule',
            name='StartTime',
            field=models.TimeField(default=b'08:00'),
        ),
    ]
