# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PatientScheduling', '0002_auto_20160215_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nurseschedule',
            name='id',
        ),
        migrations.AddField(
            model_name='nurseschedule',
            name='LunchDuration',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='nurseschedule',
            name='Team',
            field=models.CharField(default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='nurseschedule',
            name='EndTime',
            field=models.TimeField(default='5:00'),
        ),
        migrations.AlterField(
            model_name='nurseschedule',
            name='LunchTime',
            field=models.TimeField(default='12:00'),
        ),
        migrations.AlterField(
            model_name='nurseschedule',
            name='NurseID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nurseschedule',
            name='StartTime',
            field=models.TimeField(default='8:00'),
        ),
        migrations.DeleteModel(
            name='Nurse',
        ),
    ]
