# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PatientScheduling', '0002_auto_20160502_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chemotherapydrug',
            name='EarliestTime',
        ),
        migrations.RemoveField(
            model_name='chemotherapydrug',
            name='LatestTime',
        ),
        migrations.AddField(
            model_name='chemotherapydrug',
            name='Earliest Schedule Time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chemotherapydrug',
            name='Latest Schedule Time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chemotherapydrug',
            name='Other Rules',
            field=models.TextField(blank=True, null=True),
        ),
    ]
