# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 06:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PatientScheduling', '0002_auto_20160511_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedschedule',
            name='TimeSlots',
            field=models.ForeignKey(default='temp', on_delete=django.db.models.deletion.CASCADE, to='PatientScheduling.SavedTimeSlotGroup'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='savedtimeslot',
            name='Group',
            field=models.ForeignKey(default='temp', on_delete=django.db.models.deletion.CASCADE, to='PatientScheduling.SavedTimeSlotGroup'),
            preserve_default=False,
        ),
    ]
