# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-06 18:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PatientScheduling', '0002_minmaxtime_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='CompanyHours',
            field=models.OneToOneField(default='08:00:00', on_delete=django.db.models.deletion.CASCADE, to='PatientScheduling.MinMaxTime'),
            preserve_default=False,
        ),
    ]
