# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 02:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PatientScheduling', '0002_auto_20160427_1533'),
        ('PatientScheduling', '0002_auto_20160502_1908'),
    ]

    operations = [
    ]
