# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-06 18:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PatientScheduling', '0003_userprofile_companyhours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='CompanyHours',
        ),
    ]
