# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PatientScheduling', '0003_auto_20160219_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurseschedule',
            name='EndTime',
            field=models.TimeField(default='16:00'),
        ),
    ]
