# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 15:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PatientScheduling', '0003_auto_20160504_0826'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chemotherapydrug',
            options={'verbose_name': 'Chemotherapy Drug', 'verbose_name_plural': 'Chemotherapy Drugs'},
        ),
        migrations.AlterModelOptions(
            name='nurseschedulegroups',
            options={'verbose_name': 'RN Schedule', 'verbose_name_plural': 'RN Schedules'},
        ),
    ]
