# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-31 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PatientScheduling', '0004_savedtimeslot_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedtimeslot',
            name='TimeOfDay',
            field=models.CharField(default=b'M', max_length=1),
        ),
    ]
