# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PatientScheduling', '0004_auto_20160504_0856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chemotherapydrug',
            name='Earliest Schedule Time',
        ),
        migrations.RemoveField(
            model_name='chemotherapydrug',
            name='Latest Schedule Time',
        ),
        migrations.RemoveField(
            model_name='chemotherapydrug',
            name='Other Rules',
        ),
        migrations.AddField(
            model_name='chemotherapydrug',
            name='EarliestTime',
            field=models.TimeField(blank=True, null=True, verbose_name=b'Earliest Schedule Time'),
        ),
        migrations.AddField(
            model_name='chemotherapydrug',
            name='LatestTime',
            field=models.TimeField(blank=True, null=True, verbose_name=b'Latest Schedule Time'),
        ),
        migrations.AddField(
            model_name='chemotherapydrug',
            name='OtherRules',
            field=models.TextField(blank=True, null=True, verbose_name=b'Other Rules'),
        ),
        migrations.AlterField(
            model_name='chemotherapydrug',
            name='Name',
            field=models.CharField(max_length=60, primary_key=True, serialize=False, verbose_name=b'Name'),
        ),
        migrations.AlterField(
            model_name='nurseschedulegroups',
            name='SavedDate',
            field=models.DateTimeField(auto_now=True, verbose_name=b'Created On'),
        ),
    ]
