# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PatientScheduling', '0005_auto_20160504_0900'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savedtimeslot',
            options={'verbose_name': 'Time Slots Input', 'verbose_name_plural': 'Saved Time Slots Inputs'},
        ),
        migrations.AlterField(
            model_name='savedtimeslot',
            name='SavedDate',
            field=models.DateTimeField(auto_now=True, verbose_name=b'Created On'),
        ),
    ]
