# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 02:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PatientScheduling', '0005_auto_20160219_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NurseGroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PatientScheduling.ScheduleGroups')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='ChairID',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='Schedule',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='PatientScheduling.SavedSchedule'),
            preserve_default=False,
        ),
    ]
