# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 22:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PatientScheduling', '0007_auto_20160504_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedTimeSlotGroup',
            fields=[
                ('Name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('SavedDate', models.DateTimeField(auto_now=True, verbose_name=b'Created On')),
            ],
            options={
                'verbose_name': 'Time Slots Input',
                'verbose_name_plural': 'Saved Time Slots Inputs',
            },
        ),
        migrations.AlterModelOptions(
            name='savedtimeslot',
            options={},
        ),
        migrations.RemoveField(
            model_name='savedtimeslot',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='savedtimeslot',
            name='SavedDate',
        ),
        migrations.AlterField(
            model_name='nurseschedule',
            name='ScheduleGroupName',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='PatientScheduling.NurseScheduleGroups'),
        ),
        migrations.AddField(
            model_name='savedschedule',
            name='TimeSlots',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='PatientScheduling.SavedTimeSlotGroup'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='savedtimeslot',
            name='Group',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to='PatientScheduling.SavedTimeSlotGroup'),
            preserve_default=False,
        ),
    ]
