# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 23:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PatientScheduling', '0008_auto_20160505_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedtimeslot',
            name='Group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PatientScheduling.SavedTimeSlotGroup'),
        ),
    ]
