# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-18 21:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PatientScheduling', '0009_auto_20160505_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedschedule',
            name='TimeSlots',
        ),
    ]
