# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-26 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PatientScheduling', '0010_remove_savedschedule_timeslots'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedtimeslot',
            name='Priority',
            field=models.IntegerField(default=0),
        ),
    ]
