# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-02 01:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PatientScheduling', '0012_savedtimeslot_timeofday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedtimeslot',
            name='TimeOfDay',
        ),
    ]
